version: '3'
services:
  vyos:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: "host"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    environment:
      - VYOS_SSHKEY="ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGjW6g1Afw9A1/X9i6N3yMrFx9lZ5m7KluW0p+T1IoIYhk95Mf2HNmYMEzeaRreeQQ17SKjRt+WsnHKXYHHv/gk6ACIa8FHhhLxIA3gPLNcoh9YTlFOjtG9fj7d6L/cm92vZtun1P4MnqhSI126Zpy7uGQS1DW67g3A0K9E20iEopoH+g== sebbycorp@sebastians-mbp.lan"
